name = "demosjarco-portfolio"
pages_build_output_dir = "dist"
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat_v2"]
upload_source_maps = true

[vars]
NODE_ENV = "development"
SKIP_DEPENDENCY_INSTALL = "1"


[env.production]
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat_v2"]
upload_source_maps = true

[env.production.vars]
NODE_ENV = "production"
SKIP_DEPENDENCY_INSTALL = "1"


[dev]
local_protocol = "http"
ip = "localhost"
port = 48054
